const MINSIZEWIN = 'MINSIZEWIN';
 const RENDERPROCESSCALL = 'RENDERPROCESSCALL';
 const MAXSIZEWIN = 'MAXSIZEWIN';
 const CLOSE = 'CLOSE';
 const SHOWDIALOG = 'SHOWDIALOG';
 const DOWNLOADFILE = 'DOWNLOADFILE';
 const CHECK_FILE_EXIST = 'CHECK_FILE_EXIST';

module.exports = {
    MINSIZEWIN,
    RENDERPROCESSCALL,
    MAXSIZEWIN,
    CLOSE,
    SHOWDIALOG,
    DOWNLOADFILE,
    CHECK_FILE_EXIST
}