const MINSIZEWIN = 'MINSIZEWIN';
 const RENDERPROCESSCALL = 'RENDERPROCESSCALL';
 const MAXSIZEWIN = 'MAXSIZEWIN';
 const CLOSE = 'CLOSE';
 const SHOWDIALOG = 'SHOWDIALOG';
 const DOWNLOADFILE = 'DOWNLOADFILE';
 const CHECK_FILE_EXIST = 'CHECK_FILE_EXIST';
 const OPEN_CALL_WINDOW = 'OPEN_CALL_WINDOW';
 const CALL_WINDOW_CLOSE = 'CALL_WINDOW_CLOSE';
 const CALL_WINDOW_CLOSE_REPLY = 'CALL_WINDOW_CLOSE_REPLY';



module.exports = {
    MINSIZEWIN,
    RENDERPROCESSCALL,
    MAXSIZEWIN,
    CLOSE,
    SHOWDIALOG,
    DOWNLOADFILE,
    CHECK_FILE_EXIST,
    OPEN_CALL_WINDOW,
    CALL_WINDOW_CLOSE,
    CALL_WINDOW_CLOSE_REPLY
}