const MINSIZEWIN = 'MINSIZEWIN';
 const RENDERPROCESSCALL = 'RENDERPROCESSCALL';
 const MAXSIZEWIN = 'MAXSIZEWIN';
 const CLOSE = 'CLOSE';
 const SHOWDIALOG = 'SHOWDIALOG';
 const DOWNLOADFILE = 'DOWNLOADFILE';

module.exports = {
    MINSIZEWIN,
    RENDERPROCESSCALL,
    MAXSIZEWIN,
    CLOSE,
    SHOWDIALOG,
    DOWNLOADFILE
}